name: "ğŸ”§ test"

on: [push]

jobs:
  test:
    name: "ğŸ”§ test"
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“š checkout
        uses: actions/checkout@v4
      - name: ğŸŸ¢ node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: ğŸ“¦ install
        run: npm ci
      - name: ğŸ—ï¸ build
        run: npm run build --if-present
      - name: ğŸ§ª test
        run: npm test
